### ISSUE TITLE
Fill out the Projections table

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/card-issuance#15]

**Comment by sergfeldman** [comment]
@pavlovcik As previously mentioned I filled out the Paymentology questionnaire in a [file](https://docs.google.com/document/d/1IZO2dok5UWDwEsg5Mu7t8_HuZRCoCoFRyEK9hhTkIpU/edit?usp=sharing) available only for Ubiquity team members.
Submission of the questionnaire in the form of a publicly available PR should not be done because of the NDA.

Please review the content so I can submit it to Paymentology.
If you need to change something, please write a comment to the document.

**Comment by pavlovcik** [comment]
I just checked the document and left a comment on what you should do. This shouldn't take more than 5 minutes to do.

**Comment by sergfeldman** [comment]
@pavlovcik The bounty for Paymentology was artificially divided into 3 tasks.
The essence of this task is not only filling out the Projections table, but 1/3 of the entire task for Paymentology.
You can double-check the division in the comments https://github.com/ubiquity/card-issuance/issues/12

As I see, you removed the Price label from this task, which means I will not receive payment for it.
From the point of view of a bounty hunter, it looks like after completing a task, the DevPool reduces the total payment from the amount that was determined at the beginning of the task. 

Please clarify your position on this matter.

**Comment by pavlovcik** [comment]
https://gnosisscan.io/tx/0xf295a5eaba7e03274cd3eed059b8ebb3f3dc4bc8639ed8175bf14675e853402f

This was during the conference so I had basically zero time to look into this. It's my fault for not actually checking the scope of work before approving the budget.

**Comment by sergfeldman** [comment]
@pavlovcik Thank you for the payment! 

It is hard to estimate such tasks beforehand.
Filling out this questionnaire for Paymentology has already taken 2 times longer due to unplanned research of BIN sponsors. 

After meeting with Paynentology next week I will probably have to change the answers to some questions one more time.
