### ISSUE TITLE
Fill out answers to the rest of the questions

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/card-issuance#16]

**Comment by sergfeldman** [comment]
@pavlovcik As previously mentioned I filled out the Paymentology questionnaire in a [file](https://docs.google.com/document/d/1IZO2dok5UWDwEsg5Mu7t8_HuZRCoCoFRyEK9hhTkIpU/edit?usp=sharing) available only for Ubiquity team members.
Submission of the questionnaire in the form of a publicly available PR should not be done because of the NDA.

Please review the content so I can submit it to Paymentology.
If you need to change something, please write a comment to the document.

**Comment by pavlovcik** [comment]
I reviewed. Thanks!

**Comment by pavlovcik** [comment]
@sergfeldman you can comment, reassign yourself, and close as complete to collect the payment.

**Comment by sergfeldman** [comment]
> @sergfeldman you can comment, reassign yourself, and close as complete to collect the payment. In order to keep things moving, you should definitely be working with @Draeieg on reviews.

**Comment by sergfeldman** [comment]
Thank you, claimed 200 wxdai

Conversation Rewards to be claimed later
